# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# Block Designs: bd/mb_subsystem/mb_subsystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem || ORIG_REF_NAME==mb_subsystem}]

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mig_7series_0_0 || ORIG_REF_NAME==mb_subsystem_mig_7series_0_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_v10_0 || ORIG_REF_NAME==mb_subsystem_dlmb_v10_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_1/mb_subsystem_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_v10_1 || ORIG_REF_NAME==mb_subsystem_ilmb_v10_1}]

# IP: bd/mb_subsystem/ip/mb_subsystem_dlmb_bram_if_cntlr_0/mb_subsystem_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_subsystem_dlmb_bram_if_cntlr_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_ilmb_bram_if_cntlr_1/mb_subsystem_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_subsystem_ilmb_bram_if_cntlr_1}]

# IP: bd/mb_subsystem/ip/mb_subsystem_lmb_bram_0/mb_subsystem_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_lmb_bram_0 || ORIG_REF_NAME==mb_subsystem_lmb_bram_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_periph_0/mb_subsystem_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_periph_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_intc_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_xlconcat_0/mb_subsystem_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_xlconcat_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mdm_1_0 || ORIG_REF_NAME==mb_subsystem_mdm_1_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_proc_sys_reset_1_0/mb_subsystem_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_proc_sys_reset_1_0 || ORIG_REF_NAME==mb_subsystem_proc_sys_reset_1_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_timer_0_0/mb_subsystem_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_timer_0_0 || ORIG_REF_NAME==mb_subsystem_axi_timer_0_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_0/mb_subsystem_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_bram_ctrl_0_0 || ORIG_REF_NAME==mb_subsystem_axi_bram_ctrl_0_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_blk_mem_gen_0_1/mb_subsystem_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_blk_mem_gen_0_1 || ORIG_REF_NAME==mb_subsystem_blk_mem_gen_0_1}]

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_mem_intercon_1/mb_subsystem_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_mem_intercon_1 || ORIG_REF_NAME==mb_subsystem_axi_mem_intercon_1}]

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/mb_subsystem_axi_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_ethernet_0_0 || ORIG_REF_NAME==mb_subsystem_axi_ethernet_0_0}]

# Block Designs: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/bd_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0 || ORIG_REF_NAME==bd_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_0/bd_0_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_eth_buf_0 || ORIG_REF_NAME==bd_0_eth_buf_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/bd_0_eth_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_eth_mac_0 || ORIG_REF_NAME==bd_0_eth_mac_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_dma_0/mb_subsystem_axi_ethernet_0_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_ethernet_0_dma_0 || ORIG_REF_NAME==mb_subsystem_axi_ethernet_0_dma_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_0_0/mb_subsystem_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_0_0 || ORIG_REF_NAME==mb_subsystem_clk_wiz_0_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_xbar_1/mb_subsystem_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_xbar_1 || ORIG_REF_NAME==mb_subsystem_xbar_1}]

# IP: bd/mb_subsystem/ip/mb_subsystem_xbar_0/mb_subsystem_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_xbar_0 || ORIG_REF_NAME==mb_subsystem_xbar_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_s00_regslice_0/mb_subsystem_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s00_regslice_0 || ORIG_REF_NAME==mb_subsystem_s00_regslice_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_s00_data_fifo_0/mb_subsystem_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s00_data_fifo_0 || ORIG_REF_NAME==mb_subsystem_s00_data_fifo_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_s01_regslice_0/mb_subsystem_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s01_regslice_0 || ORIG_REF_NAME==mb_subsystem_s01_regslice_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_s01_data_fifo_0/mb_subsystem_s01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s01_data_fifo_0 || ORIG_REF_NAME==mb_subsystem_s01_data_fifo_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_s02_regslice_0/mb_subsystem_s02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s02_regslice_0 || ORIG_REF_NAME==mb_subsystem_s02_regslice_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_s02_data_fifo_0/mb_subsystem_s02_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s02_data_fifo_0 || ORIG_REF_NAME==mb_subsystem_s02_data_fifo_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_s03_regslice_0/mb_subsystem_s03_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s03_regslice_0 || ORIG_REF_NAME==mb_subsystem_s03_regslice_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_s03_data_fifo_0/mb_subsystem_s03_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s03_data_fifo_0 || ORIG_REF_NAME==mb_subsystem_s03_data_fifo_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_s04_regslice_0/mb_subsystem_s04_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s04_regslice_0 || ORIG_REF_NAME==mb_subsystem_s04_regslice_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_s04_data_fifo_0/mb_subsystem_s04_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s04_data_fifo_0 || ORIG_REF_NAME==mb_subsystem_s04_data_fifo_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_m00_regslice_0/mb_subsystem_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_m00_regslice_0 || ORIG_REF_NAME==mb_subsystem_m00_regslice_0}]

# IP: bd/mb_subsystem/ip/mb_subsystem_m01_regslice_0/mb_subsystem_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_m01_regslice_0 || ORIG_REF_NAME==mb_subsystem_m01_regslice_0}]

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/constraints/mb_subsystem_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mig_7series_0_0 || ORIG_REF_NAME==mb_subsystem_mig_7series_0_0}]

# XDC: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/constraints/mb_subsystem_mig_7series_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mig_7series_0_0 || ORIG_REF_NAME==mb_subsystem_mig_7series_0_0}]

# XDC: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_v10_0 || ORIG_REF_NAME==mb_subsystem_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_1/mb_subsystem_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_v10_1 || ORIG_REF_NAME==mb_subsystem_ilmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_1/mb_subsystem_ilmb_v10_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_dlmb_bram_if_cntlr_0/mb_subsystem_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_ilmb_bram_if_cntlr_1/mb_subsystem_ilmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_lmb_bram_0/mb_subsystem_lmb_bram_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_mdm_1_0 || ORIG_REF_NAME==mb_subsystem_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_proc_sys_reset_1_0/mb_subsystem_proc_sys_reset_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_proc_sys_reset_1_0 || ORIG_REF_NAME==mb_subsystem_proc_sys_reset_1_0}]

# XDC: bd/mb_subsystem/ip/mb_subsystem_proc_sys_reset_1_0/mb_subsystem_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_proc_sys_reset_1_0 || ORIG_REF_NAME==mb_subsystem_proc_sys_reset_1_0}]

# XDC: bd/mb_subsystem/ip/mb_subsystem_proc_sys_reset_1_0/mb_subsystem_proc_sys_reset_1_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_timer_0_0/mb_subsystem_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_timer_0_0 || ORIG_REF_NAME==mb_subsystem_axi_timer_0_0}]

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_timer_0_0/mb_subsystem_axi_timer_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_0/mb_subsystem_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_blk_mem_gen_0_1/mb_subsystem_blk_mem_gen_0_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_0/bd_0_eth_buf_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_buf_0 || ORIG_REF_NAME==bd_0_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_0_eth_buf_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_buf_0 || ORIG_REF_NAME==bd_0_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_0_eth_buf_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_mac_0 || ORIG_REF_NAME==bd_0_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_mac_0 || ORIG_REF_NAME==bd_0_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_mac_0 || ORIG_REF_NAME==bd_0_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/bd_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/synth/mb_subsystem_axi_ethernet_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_dma_0/mb_subsystem_axi_ethernet_0_dma_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_dma_0/mb_subsystem_axi_ethernet_0_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_ethernet_0_dma_0 || ORIG_REF_NAME==mb_subsystem_axi_ethernet_0_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_dma_0/mb_subsystem_axi_ethernet_0_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_ethernet_0_dma_0 || ORIG_REF_NAME==mb_subsystem_axi_ethernet_0_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_0_0/mb_subsystem_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_0_0 || ORIG_REF_NAME==mb_subsystem_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_0_0/mb_subsystem_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_0_0 || ORIG_REF_NAME==mb_subsystem_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_0_0/mb_subsystem_clk_wiz_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_xbar_1/mb_subsystem_xbar_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_xbar_0/mb_subsystem_xbar_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s00_regslice_0/mb_subsystem_s00_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s00_data_fifo_0/mb_subsystem_s00_data_fifo_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s01_regslice_0/mb_subsystem_s01_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s01_data_fifo_0/mb_subsystem_s01_data_fifo_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s02_regslice_0/mb_subsystem_s02_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s02_data_fifo_0/mb_subsystem_s02_data_fifo_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s03_regslice_0/mb_subsystem_s03_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s03_data_fifo_0/mb_subsystem_s03_data_fifo_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s04_regslice_0/mb_subsystem_s04_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s04_data_fifo_0/mb_subsystem_s04_data_fifo_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_m00_regslice_0/mb_subsystem_m00_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_m01_regslice_0/mb_subsystem_m01_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/mb_subsystem_ooc.xdc
