# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# Block Designs: bd/mb_ethernet/mb_ethernet.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet || ORIG_REF_NAME==mb_ethernet}]

# IP: bd/mb_ethernet/ip/mb_ethernet_microblaze_0_0/mb_ethernet_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_microblaze_0_0 || ORIG_REF_NAME==mb_ethernet_microblaze_0_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_mig_7series_0_0/mb_ethernet_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_mig_7series_0_0 || ORIG_REF_NAME==mb_ethernet_mig_7series_0_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_dlmb_v10_0/mb_ethernet_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_dlmb_v10_0 || ORIG_REF_NAME==mb_ethernet_dlmb_v10_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_ilmb_v10_0/mb_ethernet_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_ilmb_v10_0 || ORIG_REF_NAME==mb_ethernet_ilmb_v10_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_dlmb_bram_if_cntlr_0/mb_ethernet_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_ethernet_dlmb_bram_if_cntlr_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_ilmb_bram_if_cntlr_0/mb_ethernet_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_ethernet_ilmb_bram_if_cntlr_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_lmb_bram_0/mb_ethernet_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_lmb_bram_0 || ORIG_REF_NAME==mb_ethernet_lmb_bram_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_microblaze_0_axi_periph_0/mb_ethernet_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_ethernet_microblaze_0_axi_periph_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_microblaze_0_axi_intc_0/mb_ethernet_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_ethernet_microblaze_0_axi_intc_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_microblaze_0_xlconcat_0/mb_ethernet_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_ethernet_microblaze_0_xlconcat_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_mdm_1_0/mb_ethernet_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_mdm_1_0 || ORIG_REF_NAME==mb_ethernet_mdm_1_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_rst_mig_7series_0_100M_0/mb_ethernet_rst_mig_7series_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==mb_ethernet_rst_mig_7series_0_100M_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_axi_timer_0_0/mb_ethernet_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_axi_timer_0_0 || ORIG_REF_NAME==mb_ethernet_axi_timer_0_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_axi_uartlite_0_0/mb_ethernet_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_axi_uartlite_0_0 || ORIG_REF_NAME==mb_ethernet_axi_uartlite_0_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_xbar_0/mb_ethernet_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_xbar_0 || ORIG_REF_NAME==mb_ethernet_xbar_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_axi_bram_ctrl_0_0/mb_ethernet_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_axi_bram_ctrl_0_0 || ORIG_REF_NAME==mb_ethernet_axi_bram_ctrl_0_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_blk_mem_gen_0_0/mb_ethernet_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_blk_mem_gen_0_0 || ORIG_REF_NAME==mb_ethernet_blk_mem_gen_0_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_axi_mem_intercon_0/mb_ethernet_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_axi_mem_intercon_0 || ORIG_REF_NAME==mb_ethernet_axi_mem_intercon_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_xbar_1/mb_ethernet_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_xbar_1 || ORIG_REF_NAME==mb_ethernet_xbar_1}]

# IP: bd/mb_ethernet/ip/mb_ethernet_axi_ethernetlite_0_0/mb_ethernet_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_axi_ethernetlite_0_0 || ORIG_REF_NAME==mb_ethernet_axi_ethernetlite_0_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_s00_data_fifo_0/mb_ethernet_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_s00_data_fifo_0 || ORIG_REF_NAME==mb_ethernet_s00_data_fifo_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_auto_ds_0/mb_ethernet_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_auto_ds_0 || ORIG_REF_NAME==mb_ethernet_auto_ds_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_auto_pc_0/mb_ethernet_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_auto_pc_0 || ORIG_REF_NAME==mb_ethernet_auto_pc_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_auto_us_df_0/mb_ethernet_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_auto_us_df_0 || ORIG_REF_NAME==mb_ethernet_auto_us_df_0}]

# IP: bd/mb_ethernet/ip/mb_ethernet_auto_us_df_1/mb_ethernet_auto_us_df_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_auto_us_df_1 || ORIG_REF_NAME==mb_ethernet_auto_us_df_1}]

# XDC: bd/mb_ethernet/ip/mb_ethernet_microblaze_0_0/mb_ethernet_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_ethernet_microblaze_0_0 || ORIG_REF_NAME==mb_ethernet_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_ethernet/ip/mb_ethernet_microblaze_0_0/mb_ethernet_microblaze_0_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_mig_7series_0_0/mb_ethernet_mig_7series_0_0/user_design/constraints/mb_ethernet_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_mig_7series_0_0 || ORIG_REF_NAME==mb_ethernet_mig_7series_0_0}]

# XDC: bd/mb_ethernet/ip/mb_ethernet_mig_7series_0_0/mb_ethernet_mig_7series_0_0/user_design/constraints/mb_ethernet_mig_7series_0_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_mig_7series_0_0/mb_ethernet_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_mig_7series_0_0 || ORIG_REF_NAME==mb_ethernet_mig_7series_0_0}]

# XDC: bd/mb_ethernet/ip/mb_ethernet_dlmb_v10_0/mb_ethernet_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_ethernet_dlmb_v10_0 || ORIG_REF_NAME==mb_ethernet_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_ethernet/ip/mb_ethernet_dlmb_v10_0/mb_ethernet_dlmb_v10_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_ilmb_v10_0/mb_ethernet_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_ethernet_ilmb_v10_0 || ORIG_REF_NAME==mb_ethernet_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_ethernet/ip/mb_ethernet_ilmb_v10_0/mb_ethernet_ilmb_v10_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_dlmb_bram_if_cntlr_0/mb_ethernet_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_ilmb_bram_if_cntlr_0/mb_ethernet_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_lmb_bram_0/mb_ethernet_lmb_bram_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_microblaze_0_axi_intc_0/mb_ethernet_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_ethernet_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_ethernet_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_ethernet/ip/mb_ethernet_microblaze_0_axi_intc_0/mb_ethernet_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_ethernet_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_ethernet_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_ethernet/ip/mb_ethernet_microblaze_0_axi_intc_0/mb_ethernet_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_mdm_1_0/mb_ethernet_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_ethernet_mdm_1_0 || ORIG_REF_NAME==mb_ethernet_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_ethernet/ip/mb_ethernet_mdm_1_0/mb_ethernet_mdm_1_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_rst_mig_7series_0_100M_0/mb_ethernet_rst_mig_7series_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==mb_ethernet_rst_mig_7series_0_100M_0}]

# XDC: bd/mb_ethernet/ip/mb_ethernet_rst_mig_7series_0_100M_0/mb_ethernet_rst_mig_7series_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==mb_ethernet_rst_mig_7series_0_100M_0}]

# XDC: bd/mb_ethernet/ip/mb_ethernet_rst_mig_7series_0_100M_0/mb_ethernet_rst_mig_7series_0_100M_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_axi_timer_0_0/mb_ethernet_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_axi_timer_0_0 || ORIG_REF_NAME==mb_ethernet_axi_timer_0_0}]

# XDC: bd/mb_ethernet/ip/mb_ethernet_axi_timer_0_0/mb_ethernet_axi_timer_0_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_axi_uartlite_0_0/mb_ethernet_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_ethernet_axi_uartlite_0_0 || ORIG_REF_NAME==mb_ethernet_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_ethernet/ip/mb_ethernet_axi_uartlite_0_0/mb_ethernet_axi_uartlite_0_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_axi_uartlite_0_0/mb_ethernet_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_ethernet_axi_uartlite_0_0 || ORIG_REF_NAME==mb_ethernet_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_ethernet/ip/mb_ethernet_xbar_0/mb_ethernet_xbar_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_axi_bram_ctrl_0_0/mb_ethernet_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_blk_mem_gen_0_0/mb_ethernet_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_xbar_1/mb_ethernet_xbar_1_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_axi_ethernetlite_0_0/mb_ethernet_axi_ethernetlite_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_axi_ethernetlite_0_0 || ORIG_REF_NAME==mb_ethernet_axi_ethernetlite_0_0}]

# XDC: bd/mb_ethernet/ip/mb_ethernet_axi_ethernetlite_0_0/mb_ethernet_axi_ethernetlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_axi_ethernetlite_0_0 || ORIG_REF_NAME==mb_ethernet_axi_ethernetlite_0_0}]

# XDC: bd/mb_ethernet/ip/mb_ethernet_axi_ethernetlite_0_0/mb_ethernet_axi_ethernetlite_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ethernet_axi_ethernetlite_0_0 || ORIG_REF_NAME==mb_ethernet_axi_ethernetlite_0_0}]

# XDC: bd/mb_ethernet/ip/mb_ethernet_axi_ethernetlite_0_0/mb_ethernet_axi_ethernetlite_0_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_s00_data_fifo_0/mb_ethernet_s00_data_fifo_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_auto_ds_0/mb_ethernet_auto_ds_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_auto_ds_0/mb_ethernet_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_ethernet_auto_ds_0 || ORIG_REF_NAME==mb_ethernet_auto_ds_0}] {/inst }]/inst ]]

# XDC: bd/mb_ethernet/ip/mb_ethernet_auto_pc_0/mb_ethernet_auto_pc_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_auto_us_df_0/mb_ethernet_auto_us_df_0_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_auto_us_df_0/mb_ethernet_auto_us_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_ethernet_auto_us_df_0 || ORIG_REF_NAME==mb_ethernet_auto_us_df_0}] {/inst }]/inst ]]

# XDC: bd/mb_ethernet/ip/mb_ethernet_auto_us_df_1/mb_ethernet_auto_us_df_1_ooc.xdc

# XDC: bd/mb_ethernet/ip/mb_ethernet_auto_us_df_1/mb_ethernet_auto_us_df_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_ethernet_auto_us_df_1 || ORIG_REF_NAME==mb_ethernet_auto_us_df_1}] {/inst }]/inst ]]

# XDC: bd/mb_ethernet/mb_ethernet_ooc.xdc
