# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7k325tffg900-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Design_checkkc705/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Design_checkkc705/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.1 [current_project]
add_files C:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/mb_ethernet.bd
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_microblaze_0_0/mb_ethernet_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_microblaze_0_0/mb_ethernet_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_mig_7series_0_0/mb_ethernet_mig_7series_0_0/user_design/constraints/mb_ethernet_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_mig_7series_0_0/mb_ethernet_mig_7series_0_0/user_design/constraints/mb_ethernet_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_mig_7series_0_0/mb_ethernet_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_dlmb_v10_0/mb_ethernet_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_dlmb_v10_0/mb_ethernet_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_ilmb_v10_0/mb_ethernet_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_ilmb_v10_0/mb_ethernet_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_dlmb_bram_if_cntlr_0/mb_ethernet_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_ilmb_bram_if_cntlr_0/mb_ethernet_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_lmb_bram_0/mb_ethernet_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_microblaze_0_axi_intc_0/mb_ethernet_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_microblaze_0_axi_intc_0/mb_ethernet_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_microblaze_0_axi_intc_0/mb_ethernet_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_mdm_1_0/mb_ethernet_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_mdm_1_0/mb_ethernet_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_rst_mig_7series_0_100M_0/mb_ethernet_rst_mig_7series_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_rst_mig_7series_0_100M_0/mb_ethernet_rst_mig_7series_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_rst_mig_7series_0_100M_0/mb_ethernet_rst_mig_7series_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_axi_timer_0_0/mb_ethernet_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_axi_timer_0_0/mb_ethernet_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_axi_uartlite_0_0/mb_ethernet_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_axi_uartlite_0_0/mb_ethernet_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_axi_uartlite_0_0/mb_ethernet_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_xbar_0/mb_ethernet_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_axi_bram_ctrl_0_0/mb_ethernet_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_blk_mem_gen_0_0/mb_ethernet_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_xbar_1/mb_ethernet_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_axi_ethernetlite_0_0/mb_ethernet_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_axi_ethernetlite_0_0/mb_ethernet_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_axi_ethernetlite_0_0/mb_ethernet_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_axi_ethernetlite_0_0/mb_ethernet_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_s00_data_fifo_0/mb_ethernet_s00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_auto_ds_0/mb_ethernet_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_auto_ds_0/mb_ethernet_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_auto_pc_0/mb_ethernet_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_auto_us_df_0/mb_ethernet_auto_us_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_auto_us_df_0/mb_ethernet_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_auto_us_df_1/mb_ethernet_auto_us_df_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/ip/mb_ethernet_auto_us_df_1/mb_ethernet_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all C:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/mb_ethernet_ooc.xdc]
set_property is_locked true [get_files C:/Design_checkkc705/project_1/project_1.srcs/sources_1/bd/mb_ethernet/mb_ethernet.bd]

read_verilog -library xil_defaultlib C:/Design_checkkc705/project_1/project_1.srcs/sources_1/imports/hdl/mb_ethernet_wrapper.v
read_xdc C:/Design_checkkc705/project_1/project_1.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files C:/Design_checkkc705/project_1/project_1.srcs/constrs_1/new/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file mb_ethernet_wrapper.hwdef }
synth_design -top mb_ethernet_wrapper -part xc7k325tffg900-2
write_checkpoint mb_ethernet_wrapper.dcp
catch { report_utilization -file mb_ethernet_wrapper_utilization_synth.rpt -pb mb_ethernet_wrapper_utilization_synth.pb }
